export const Professors = [
  {
    image: 'https://iiitd.ac.in/sites/default/files/images/faculty/vabrol.jpg',
    name: 'Vinayak Abrol',
    website: 'https://iiitd.ac.in/vabrol',
    jobTitle: 'Assistant Professor (CSE)',
    education: 'PhD (2018), IIT Mandi, India',
    type: 'Faculty',
    additionalInfo: '',
    DBLP: '136/4698',
    GoogleScholar:
      'https://scholar.google.com/citations?user=13e0zscAAAAJ&hl=en&oi=ao',
    DOR: '',
    DOJ: '01-Jan-21',
  },
  {
    image: 'https://iiitd.ac.in/sites/default/files/images/faculty/sdeb.jpg',
    name: 'Sujay Deb',
    website: 'https://iiitd.ac.in/sdeb',
    jobTitle: 'Associate Professor (ECE, CSE)',
    education: 'PhD (2012), Washington State University, USA',
    type: 'Faculty',
    additionalInfo: '',
    DBLP: '61/8572',
    GoogleScholar:
      'https://scholar.google.com/citations?hl=en&user=e3z7tT0AAAAJ',
    DOR: '',
    DOJ: '25-Jun-12',
  },
  {
    image: 'https://iiitd.ac.in/sites/default/files/images/faculty/rinku.jpg',
    name: 'Rinku Shah',
    website: 'https://iiitd.ac.in/rinku',
    jobTitle: 'Assistant Professor (CSE)',
    education: 'PhD (2021), IIT Bombay, India',
    type: 'Faculty',
    additionalInfo: '',
    DBLP: '146/0131',
    GoogleScholar:
      'https://scholar.google.com/citations?hl=en&user=jNhSvOEAAAAJ',
    DOR: '',
    DOJ: '15-Jul-21',
  },
  {
    image: 'https://iiitd.ac.in/sites/default/files/images/faculty/bapi.jpg',
    name: 'Bapi Chatterjee',
    website: 'https://iiitd.ac.in/bapi',
    jobTitle: 'Assistant Professor (CSE)',
    education: 'PhD (2018), Chalmers University of Technology, Sweden',
    type: 'Faculty',
    additionalInfo: '',
    DBLP: '117/6988',
    GoogleScholar:
      'https://scholar.google.com/citations?user=ILI-_h4AAAAJ&hl=en&oi=ao',
    DOR: '',
    DOJ: '02-Aug-21',
  },
  {
    image: 'https://iiitd.ac.in/sites/default/files/images/faculty/arani.jpg',
    name: 'Arani Bhattacharya',
    website: 'https://iiitd.ac.in/arani',
    jobTitle: 'Assistant Professor (CSE)',
    education: 'PhD (2019), Stony Brook University, USA',
    type: 'Faculty',
    additionalInfo: '',
    DBLP: '139/0489',
    GoogleScholar:
      'https://scholar.google.com/citations?user=YjiIDkjozUcC&hl=en&oi=ao',
    DOR: '',
    DOJ: '08-Oct-20',
  },
  {
    image: 'https://iiitd.ac.in/sites/default/files/images/faculty/angshul.jpg',
    name: 'Angshul Majumdar',
    website: 'https://iiitd.ac.in/angshul',
    jobTitle: 'Associate Professor (ECE, CSE)',
    education: 'PhD (2012), University of British Columbia, Canada',
    type: 'Faculty',
    additionalInfo: '',
    DBLP: '69/4115',
    GoogleScholar:
      'https://scholar.google.com/citations?user=nwNIkAUAAAAJ&hl=en&oi=ao',
    DOR: '',
    DOJ: '01-Oct-12',
  },
  {
    image:
      'https://iiitd.ac.in/sites/default/files/images/faculty/subramanyam.jpg',
    name: 'A V Subramanyam',
    website: 'https://iiitd.ac.in/subramanyam',
    jobTitle: 'Associate Professor (ECE, CSE)',
    education: 'PhD (2012), Nanyang Technological University, Singapore',
    type: 'Faculty',
    additionalInfo: '',
    DBLP: '232/6141',
    GoogleScholar:
      'https://scholar.google.com/citations?user=aPDRgKAAAAAJ&hl=en&oi=ao',
    DOR: '',
    DOJ: '10-Jun-13',
  },
  {
    image: 'https://iiitd.ac.in/sites/default/files/images/faculty/arunb.jpg',
    name: 'Arun Balaji Buduru',
    website: 'https://iiitd.ac.in/arunb',
    jobTitle: 'Assistant Professor (CSE)',
    education: 'PhD (2016), Arizona State University, USA',
    type: 'Faculty',
    additionalInfo: '',
    DBLP: '128/4273',
    GoogleScholar:
      'https://scholar.google.com/citations?hl=en&user=TmGAyPYAAAAJ',
    DOR: '',
    DOJ: '19-Dec-16',
  },
  {
    image:
      'https://iiitd.ac.in/sites/default/files/images/faculty/debajyoti.jpg',
    name: 'Debajyoti Bera',
    website: 'https://iiitd.ac.in/dbera',
    jobTitle: 'Associate Professor (CSE)',
    education: 'PhD (2009), Boston University, USA',
    type: 'Faculty',
    additionalInfo: '',
    DBLP: '46/6276',
    GoogleScholar:
      'https://scholar.google.com/citations?hl=en&user=kv2a54oAAAAJ',
    DOR: '',
    DOJ: '22-Jan-10',
  },
  {
    image: 'https://iiitd.ac.in/sites/default/files/images/faculty/debarka.jpg',
    name: 'Debarka Sengupta',
    website: 'https://iiitd.ac.in/debarka',
    jobTitle: 'Associate Professor (CSE, CB)',
    education: 'PhD, Jadavpur University, India',
    type: 'Faculty',
    additionalInfo: '',
    DBLP: '14/11132',
    GoogleScholar:
      'https://scholar.google.com/citations?user=b-57qe4AAAAJ&hl=en&oi=ao',
    DOR: '',
    DOJ: '16-Jan-17',
  },
  {
    image:
      'https://iiitd.ac.in/sites/default/files/images/faculty/Jainendra.jpg',
    name: 'Jainendra Shukla',
    website: 'https://iiitd.ac.in/jainendra',
    jobTitle: 'Assistant Professor (CSE, HCD)',
    education: 'PhD (2018), Universitat Rovira i Virgili (URV), Spain',
    type: 'Faculty',
    additionalInfo: '',
    DBLP: '117/9926',
    GoogleScholar:
      'https://scholar.google.com/citations?user=QCZleNQAAAAJ&hl=en&oi=ao',
    DOR: '',
    DOJ: '14-Jan-19',
  },
  {
    image:
      'https://iiitd.ac.in/sites/default/files/images/faculty/koteswar.jpg',
    name: 'Koteswar Rao Jerripothula',
    website: 'https://iiitd.ac.in/koteswar',
    jobTitle: 'Assistant Professor (CSE)',
    education: 'PhD (2017), Nanyang Technological University (NTU), Singapore',
    type: 'Faculty',
    additionalInfo: '',
    DBLP: '158/9790',
    GoogleScholar:
      'https://scholar.google.com/citations?user=QgTEe-gAAAAJ&hl=en&oi=ao',
    DOR: '',
    DOJ: '02-May-20',
  },
  {
    image: 'https://iiitd.ac.in/sites/default/files/images/faculty/shad.jpg',
    name: 'Md. Shad Akhtar',
    website: 'https://iiitd.ac.in/shad',
    jobTitle: 'Assistant Professor (CSE)',
    education: 'PhD (2019), IIT Patna, India',
    type: 'Faculty',
    additionalInfo: '',
    DBLP: '184/8579',
    GoogleScholar:
      'https://scholar.google.com/citations?user=KUcO6LAAAAAJ&hl=en&oi=ao',
    DOR: '',
    DOJ: '01-Mar-20',
  },
  {
    image: 'https://iiitd.ac.in/sites/default/files/public/faculty/mukesh.jpg',
    name: 'Mukesh Mohania',
    website: 'https://iiitd.ac.in/mukesh',
    jobTitle: 'Professor (CSE) ',
    education: 'PhD (1995), Indian Institute of Technology Bombay, India',
    type: 'Faculty',
    additionalInfo: '',
    DBLP: '85/6670',
    GoogleScholar:
      'https://scholar.google.com/citations?user=zgaqvNQAAAAJ&hl=en&oi=ao',
    DOR: '',
    DOJ: '19-Nov-19',
  },
  {
    image:
      'https://iiitd.ac.in/sites/default/files/images/faculty/mukulikam.jpg',
    name: 'Mukulika Maity',
    website: 'https://iiitd.ac.in/mukulika',
    jobTitle: 'Assistant Professor (CSE)',
    education: 'PhD (2016), IIT Bombay, India',
    type: 'Faculty',
    additionalInfo: '',
    DBLP: '157/1298',
    GoogleScholar:
      'https://scholar.google.com/citations?hl=en&user=F5sooVMAAAAJ',
    DOR: '',
    DOJ: '30-Nov-16',
  },
  {
    image: 'https://iiitd.ac.in/sites/default/files/images/faculty/ojaswa.jpg',
    name: 'Ojaswa Sharma',
    website: 'https://iiitd.ac.in/ojaswa',
    jobTitle: 'Head, Associate Professor (CSE, Math) ',
    education: 'PhD (2010), Technical University of Denmark, Denmark',
    type: 'Faculty',
    additionalInfo: '',
    DBLP: '08/4556',
    GoogleScholar:
      'https://scholar.google.com/citations?hl=en&user=jikZgTsAAAAJ',
    DOR: '',
    DOJ: '02-Jun-14',
  },
  {
    image: 'https://iiitd.ac.in/sites/default/files/images/faculty/jalote.jpg',
    name: 'Pankaj Jalote',
    website: 'https://iiitd.ac.in/jalote',
    jobTitle: 'Distinguished Professor (CSE)',
    education: 'PhD (1985), University of Illinois at Urbana Champaign, USA',
    type: 'Faculty',
    additionalInfo: '',
    DBLP: 'j/PankajJalote',
    GoogleScholar:
      'https://scholar.google.com/citations?hl=en&user=S8tJjYgAAAAJ',
    DOR: '',
    DOJ: '29-Aug-08',
  },
  {
    image:
      'https://iiitd.ac.in/sites/default/files/images/faculty/piyuskedia.jpg',
    name: 'Piyus Kedia',
    website: 'https://iiitd.ac.in/piyus',
    jobTitle: 'Assistant Professor (CSE)',
    education: 'PhD (2018), IIT-Delhi, India',
    type: 'Faculty',
    additionalInfo: '',
    DBLP: '201/4871',
    GoogleScholar:
      'https://scholar.google.com/citations?user=f-4PIh4AAAAJ&hl=en&oi=ao',
    DOR: '',
    DOJ: '03-Jan-18',
  },
  {
    image:
      'https://iiitd.ac.in/sites/default/files/images/faculty/puspendra.jpg',
    name: 'Pushpendra Singh',
    website: 'https://iiitd.ac.in/pushpendra',
    jobTitle: 'Professor (CSE)',
    education: 'PhD (2004), Inria-Rennes, University de Rennes 1, France',
    type: 'Faculty',
    additionalInfo: '',
    DBLP: '55/1719-1',
    GoogleScholar: 'https://scholar.google.com/citations?user=FniYr_MAAAAJ',
    DOR: '',
    DOJ: '30-Oct-09',
  },
  {
    image: 'https://iiitd.ac.in/sites/default/files/images/faculty/ratn.jpg',
    name: 'Rajiv Ratn Shah',
    website: 'https://iiitd.ac.in/rajivratn',
    jobTitle: 'Head (HCD), Assistant Professor (CSE, HCD)',
    education: 'PhD (2017), National University of Singapore, Singapore',
    type: 'Faculty',
    additionalInfo: '',
    DBLP: '134/3502',
    GoogleScholar:
      'https://scholar.google.com/citations?user=WAChZv4AAAAJ&hl=en&oi=ao',
    DOR: '',
    DOJ: '30-Nov-16',
  },
  {
    image: 'https://iiitd.ac.in/sites/default/files/images/faculty/saket.jpg',
    name: 'Saket Anand',
    website: 'https://iiitd.ac.in/anands',
    jobTitle: 'Associate Professor (CSE, ECE)',
    education: 'PhD (2013), Rutgers University, USA',
    type: 'Faculty',
    additionalInfo: '',
    DBLP: '11/4747',
    GoogleScholar:
      'https://scholar.google.com/citations?user=YmYvVEQAAAAJ&hl=en&oi=ao',
    DOR: '',
    DOJ: '02-Sep-13',
  },
  {
    image:
      'https://iiitd.ac.in/sites/default/files/images/faculty/sambuddho.jpg',
    name: 'Sambuddho Chakravarty',
    website: 'https://iiitd.ac.in/sambuddho',
    jobTitle: 'Associate Professor (CSE)',
    education: 'PhD (2014), Columbia University, USA',
    type: 'Faculty',
    additionalInfo: '',
    DBLP: '95/1983',
    GoogleScholar:
      'https://scholar.google.com/citations?user=8CJgHUIAAAAJ&hl=en&oi=ao',
    DOR: '',
    DOJ: '02-Jun-14',
  },
  {
    image:
      'https://iiitd.ac.in/sites/default/files/images/faculty/subhabrata.jpg',
    name: 'Subhabrata Samajder',
    website: 'https://iiitd.ac.in/subhabrata',
    jobTitle: 'Assistant Professor (CSE)',
    education: 'PhD (2017) Indian Statistical Institute, Kolkata',
    type: 'Faculty',
    additionalInfo: '',
    DBLP: '143/4473',
    GoogleScholar:
      'https://scholar.google.com/citations?hl=en&user=FoJNBQYAAAAJ',
    DOR: '',
    DOJ: '08-May-19',
  },
  {
    image:
      'https://iiitd.ac.in/sites/default/files/images/faculty/syamantak.jpg',
    name: 'Syamantak Das',
    website: 'https://iiitd.ac.in/syamantak',
    jobTitle: 'Assistant Professor (CSE)',
    education: 'PhD (2015), IIT-Delhi, India',
    type: 'Faculty',
    additionalInfo: '',
    DBLP: '135/6297',
    GoogleScholar:
      'https://scholar.google.com/citations?user=7nBU-20AAAAJ&hl=en&oi=ao',
    DOR: '',
    DOJ: '01-Jan-18',
  },
  {
    image:
      'https://iiitd.ac.in/sites/default/files/images/faculty/diptapriyo.jpg',
    name: 'Diptapriyo Majumdar',
    website: 'https://iiitd.ac.in/diptapriyo',
    jobTitle: 'Assistant Professor (CSE)',
    education:
      'Ph.D. (2018), The Institute of Mathematical Sciences (IMSc), Chennai',
    type: 'Faculty',
    additionalInfo: '',
    DBLP: '171/3758',
    GoogleScholar:
      'https://scholar.google.com/citations?hl=en&user=uQknAL4AAAAJ',
    DOR: '',
    DOJ: '16-Dec-21',
  },
  {
    image: 'https://iiitd.ac.in/sites/default/files/images/faculty/tanmoy.jpg',
    name: 'Tanmoy Chakraborty',
    website: 'https://iiitd.ac.in/tanmoy',
    jobTitle: 'Associate Professor (CSE)',
    education: 'PhD (2015), IIT Kharagpur, India',
    type: 'Faculty',
    additionalInfo: 'On Leave',
    DBLP: '65/2136-2',
    GoogleScholar: 'https://scholar.google.co.in/citations?user=C5S9JnIAAAAJ',
    DOR: '',
    DOJ: '17-May-17',
  },
  {
    image:
      'https://iiitd.ac.in/sites/default/files/images/faculty/raghavam.jpg',
    name: 'V. Raghava Mutharaju',
    website: 'https://iiitd.ac.in/raghavam',
    jobTitle: 'Assistant Professor (CSE)',
    education: 'PhD (2016), Wright State University, USA',
    type: 'Faculty',
    additionalInfo: '',
    DBLP: '63/7446',
    GoogleScholar:
      'https://scholar.google.com/citations?hl=en&user=69pEM_YAAAAJ',
    DOR: '',
    DOJ: '09-Oct-18',
  },
  {
    image: 'https://iiitd.ac.in/sites/default/files/images/faculty/vikram.jpg',
    name: 'Vikram Goyal',
    website: 'https://iiitd.ac.in/vikram',
    jobTitle: 'Professor (CSE)',
    education: 'PhD (2009), IIT Delhi, India',
    type: 'Faculty',
    additionalInfo: '',
    DBLP: '70/6404',
    GoogleScholar:
      'https://scholar.google.com/citations?hl=en&user=YJaVmSwAAAAJ',
    DOR: '',
    DOJ: '24-Apr-09',
  },
  {
    image: 'https://iiitd.ac.in/sites/default/files/images/faculty/vivekk.jpg',
    name: 'Vivek Kumar',
    website: 'https://iiitd.ac.in/vivekk',
    jobTitle: 'Assistant Professor (CSE)',
    education: 'PhD (2014), Australian National University, Australia',
    type: 'Faculty',
    additionalInfo: '',
    DBLP: '82/2381-1',
    GoogleScholar:
      'https://scholar.google.com/citations?hl=en&user=cRZsY44AAAAJ',
    DOR: '',
    DOJ: '13-Dec-16',
  },
  {
    image: 'https://iiitd.ac.in/sites/default/files/images/faculty/bnjain.jpg',
    name: 'Bijendra Nath Jain',
    website: '',
    jobTitle: 'Visiting Distinguished Professor',
    education: 'PhD (1975), SUNY Stony Brook, USA',
    type: 'Visiting Faculty',
    additionalInfo: '',
    DBLP: 'j/BijendraNJain',
    GoogleScholar:
      'https://scholar.google.co.in/citations?view_op=list_works&hl=en&hl=en&user=hMZMd8sAAAAJ',
    DOR: '',
    DOJ: '01-Jul-19',
  },
  {
    image:
      'https://iiitd.ac.in/sites/default/files/images/faculty/anantaram.jpg',
    name: 'C. Anantaram',
    website: '',
    jobTitle: '',
    education: 'PhD (1999), IIT Bombay, India',
    type: 'Visiting Faculty',
    additionalInfo: '',
    DBLP: '30/5842',
    GoogleScholar:
      'https://scholar.google.com/citations?hl=en&user=F42M9KwAAAAJ',
    DOR: '',
    DOJ: '01-Aug-19',
  },
  {
    image:
      'https://iiitd.ac.in/sites/default/files/images/admin/staff/pritipat.jpg',
    name: 'Priti Patwal',
    website: '',
    jobTitle: 'Junior Manager (CSE)',
    education: '',
    type: 'Staff',
    additionalInfo: 'Room No. A-501 (R&D Block) pritip@iiitd.ac.in 01126907411',
    DBLP: '',
    GoogleScholar: '',
    DOR: '',
    DOJ: '',
  },
  {
    image: 'https://iiitd.ac.in/sites/default/files/images/faculty/dhruvk.jpg',
    name: 'Dhruv Kumar',
    website: 'https://www.iiitd.ac.in/dhruv',
    jobTitle: 'Assistant Professor (CSE)',
    education: 'Ph.D. (2022), University of Minnesota, Twin Cities, USA',
    type: 'Faculty',
    additionalInfo: '',
    DBLP: '159/9419-1',
    GoogleScholar: 'https://scholar.google.co.in/citations?user=cobNGlcAAAAJ',
    DOR: '',
    DOJ: '22-Aug-22',
  },
];
